### ISSUE TITLE
Reconsider the `onFrameChange` API method

### ISSUE THREAD

**Issue by Dan503** [pixfabrik/driftory-viewer#19]
As I mentioned in [this comment](https://github.com/pixfabrik/driftory-viewer/pull/17#issuecomment-715617278) `onEnd` is not the best way for the API to handle when the user tries to navigate to the next frame and there are no new frames to navigate to.

What is needed is to replace the `onFrameChange` API with new `beforeFrameChange` and `afterFrameChange` APIs (one triggers before the animation starts and the other triggers after the animation has ended).

In both `beforeFrameChange` and `afterFrameChange` pass in `isLastFrame` and `isFirstFrame` parameters. In `beforeFrameChange`, `isLastFrame` is true if the user is currently on the last frame before attempting to transition. In `afterFrameChange`, `isLastFrame` is true if the user lands on the last frame at the end of the transition.

If you are on the last frame, `beforeFrameChange` would be called but I don't think it makes sense to call `afterFrameChange` since no transition occurred.

`beforeFrameChange` in combination with is `isLastFrame` is essentially the same as using the `onNoNext` functionality.

If the user returns `false` in `beforeFrameChange`, that should prevent the frame from changing. Note that returning `undefined` should still allow the frame change to occur.

Returning `false` in `afterFrameChange` would do nothing special.

These changes will make the API much more intuitive to use in my opinion.

**Comment by Dan503** [comment]
They should both also pass in `beforeTransitionFrameIndex` and `afterTransitionFrameIndex` parameters so that people know what frames they are moving to and from.

**Comment by iangilman** [comment]
Hmm... I'll have to give some thought to this. Meanwhile, I've done what you've suggested in https://github.com/pixfabrik/driftory-viewer/pull/17#issuecomment-715617278 as part of https://github.com/pixfabrik/driftory-viewer/pull/20

**Comment by Dan503** [comment]
Actually you can still probably keep the `onNoPrevious` and `onNoNext` methods. I can see them being more intuitive to use for a lot of people.

**Comment by iangilman** [comment]
@Dan503 I'd love to hear more about your use case… If the API changes in the way you suggest, how do you expect to make use of the new events? What effect would that have on the UI? That can help me decide the best course of action.

One challenge with breaking frame changes down into before/after events is that in addition to gestures that advance you directly to the next or previous frame, the user can also freely drag the canvas around. This has the effect of taking you from frame to frame, but there's no specific before/after moment to hook those events up to. What you plan to do with those events can help me figure out how to send them in that case.

Regarding replacing onNoNext with a lone beforeFrameChange with isLastFrame and no follow-up afterFrameChange, I don't think that really works. Just because you're on the last frame before you move to another frame doesn't mean that you are trying to go to the next frame… You could be going back to the previous frame, or back to the start, or whatever. And from a coding standpoint, making decisions based on the absence of an event is problematic. I think we need an explicit "the user tried to go next past the last frame" indicator, whether it's an event or a flag on an existing event.

Anyway, knowing what effects these new events would help you create in the UI will help us figure out the right path. :-)

**Comment by Dan503** [comment]
I'll close this issue.

`onNoPrevious` and `onNoNext` and the existing `onFrameChange` code is enough for me to work with.

I don't have any strong use cases right now to require an API change.

**Comment by iangilman** [comment]
Sounds good. Let me know if/when that changes and you need more nuance :-)
