### ISSUE TITLE
Remove extra type exports from Driftory source file?

### ISSUE THREAD

**Issue by iangilman** [pixfabrik/driftory-viewer#21]
In order to integrate this new viewer into http://www.driftory.com/, I'm needing to convert it to an old-fashioned browser script (since the Driftory website code is fairly old-fashioned, being written seven years ago). I'm using http://browserify.org/ which works great, except it chokes on the two extra type exports here:

https://github.com/pixfabrik/driftory-viewer/blob/b93f24fc231cac97e164890e2825b8f04417519e/src/library/driftory.ts#L3-L4

I'm new enough to TypeScript that I don't know the purpose of those exports. Is it possible to remove them from that file and accomplish their purpose some other way? @Dan503 any thoughts?

I imagine if I'm running into this, other people might as well.

**Comment by Dan503** [comment]
Yeah, it's ok to remove them.

I only added those 2 lines as a convenience feature so that Typescript users could import the types on the same line as they are importing the viewer code.

So instead of this:

```js
import DriftoryViewer from '@driftory/viewer'
import { Comic } from '@driftory/viewer/dist/Comic.types'
```

A Typescript user could do this instead: 

```js
import DriftoryViewer, { Comic } from '@driftory/viewer'
```

If it is causing problems though then it isn't worth keeping them.
